services:
  hbutmc:
    image: itzg/minecraft-server
    container_name: hbutmc
    tty: true
    stdin_open: true
    network_mode: bridge
    restart: unless-stopped
    ports:
      - 19137:19132/udp
      - 25567:25565
      - 25577:25575
      - 25587:8100
    environment:
      - TYPE=PAPER
      - TZ=Asia/Shanghai
      - MAX_MEMORY=6G
      - EULA=TRUE
    volumes:
      - .:/data
